# Generated by Django 3.0.3 on 2020-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200225_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_date',
            field=models.DateField(auto_now=True),
        ),
    ]
