# Generated by Django 3.0.3 on 2020-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200225_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
