# Generated by Django 3.0.3 on 2020-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classone',
            options={'verbose_name': 'Questionn', 'verbose_name_plural': 'Questionnss'},
        ),
    ]
