# Generated by Django 3.0.3 on 2020-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200221_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('describe', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='classone',
            options={},
        ),
    ]
