# Generated by Django 3.0.3 on 2020-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200221_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=200)),
                ('fuction_1', models.TextField(max_length=7000)),
                ('fuction_2', models.TextField(max_length=7000)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
