# Generated by Django 3.0.3 on 2020-02-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_vocab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='fuction_1',
            new_name='function_1',
        ),
        migrations.RenameField(
            model_name='vocab',
            old_name='fuction_2',
            new_name='function_2',
        ),
    ]
