# Generated by Django 3.0.3 on 2020-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200223_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='class_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
