# Generated by Django 3.0.3 on 2020-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_vocab_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
